Repository kernelkit/infix, pull requests merged in 2024-12, with the labels that each got.

#840 Ntp status
  doc/ChangeLog.md
  doc/system.md
  src/confd/yang/confd.inc
  src/confd/yang/infix-system.yang
  src/confd/yang/infix-system@2024-11-27.yang
  src/klish-plugin-infix/xml/infix.xml
  src/statd/python/cli_pretty/cli_pretty.py
  src/statd/python/yanger/yanger.py
  src/statd/statd.c
  test/case/cli/cli-output/show-ntp.txt
  test/case/cli/run.sh
  test/case/cli/sysrepo-emulator.sh
  test/case/cli/system-output/chronyc-sources.txt
  test/case/ietf_system/Readme.adoc
  test/case/ietf_system/ietf_system.yaml
  test/case/ietf_system/ntp_client/Readme.adoc
  test/case/ietf_system/ntp_client/test.py
  test/case/ietf_system/ntp_client/topology.dot
  test/case/ietf_system/ntp_client/topology.svg
  test/infamy/ntp.py
  test/infamy/ntp_server.py
  test/infamy/topologies/1x4.dot
Labels: feature

#833 Expand mDNS settings
  board/common/rootfs/etc/sysctl.d/forwarding.conf
  board/common/rootfs/etc/sysctl.d/ipv4.conf
  board/common/rootfs/etc/sysctl.d/ipv6.conf
  board/common/rootfs/etc/sysctl.d/readme.txt
  doc/ChangeLog.md
  doc/discovery.md
  doc/networking.md
  package/skeleton-init-finit/skeleton/etc/default/avahi
  package/skeleton-init-finit/skeleton/etc/finit.d/available/avahi.conf
  package/skeleton-init-finit/skeleton/etc/finit.d/available/dropbear.conf
  package/skeleton-init-finit/skeleton/etc/finit.d/available/nginx.conf
  src/confd/src/infix-services.c
  src/confd/yang/confd.inc
  src/confd/yang/infix-services.yang
  src/confd/yang/infix-services@2024-12-02.yang
  test/case/infix_services/Readme.adoc
  test/case/infix_services/infix_services.yaml
  test/case/infix_services/mdns_allow_deny/Readme.adoc
  test/case/infix_services/mdns_allow_deny/test.py
  test/case/infix_services/mdns_allow_deny/topology.dot
  test/case/infix_services/mdns_allow_deny/topology.svg
  test/case/infix_services/services_basic/Readme.adoc
  test/case/infix_services/services_basic/test.py
  test/infamy/netconf.py
  test/infamy/netns.py
Labels: enhancement

#874 Bridge refactor
  board/common/rootfs/usr/sbin/container
  patches/conmon/2.1.8/0001-logging-Add-syslog-support.patch
  patches/podman/4.5.0/0001-Disable-pull-retry.patch
  patches/podman/4.5.0/0001-disable-pull-retry.patch
  patches/podman/4.5.0/0002-Add-log-driver-for-syslog.patch
  src/confd/bin/dagger
  src/confd/src/Makefile.am
  src/confd/src/cni.c
  src/confd/src/core.h
  src/confd/src/dagger.c
  src/confd/src/dagger.h
  src/confd/src/ieee802-ethernet-interface.c
  src/confd/src/ietf-interfaces.c
  src/confd/src/ietf-interfaces.h
  src/confd/src/ietf-ip.c
  src/confd/src/infix-if-bridge-mcd.c
  src/confd/src/infix-if-bridge-port.c
  src/confd/src/infix-if-bridge.c
  test/infamy/furl.py
Labels: ci:main

#838 Add ssh config
  board/common/rootfs/etc/ssh/sshd_config.d/var-keys.conf
  board/common/rootfs/usr/libexec/infix/mksshkey
  doc/ChangeLog.md
  doc/branding.md
  doc/management.md
  package/confd/confd.mk
  package/skeleton-init-finit/skeleton-init-finit.mk
  package/skeleton-init-finit/skeleton/etc/finit.d/available/sshd.conf
  src/confd/configure.ac
  src/confd/share/factory.d/10-infix-services.json
  src/confd/share/failure.d/10-infix-services.json
  src/confd/share/migrate/1.3/10-ssh-server.sh
  src/confd/share/migrate/1.3/Makefile.am
  src/confd/share/migrate/Makefile.am
  src/confd/share/test.d/10-infix-services.json
  src/confd/src/ietf-keystore.c
  src/confd/src/infix-services.c
  src/confd/yang/confd.inc
  src/confd/yang/infix-services.yang
  src/confd/yang/infix-services@2024-12-03.yang
  src/libsrx/src/helpers.c
  src/libsrx/src/helpers.h
  test/case/ietf_system/Readme.adoc
  test/case/ietf_system/ietf_system.yaml
  test/case/infix_services/Readme.adoc
  test/case/infix_services/infix_services.yaml
  test/case/infix_services/ssh_key_authentication/Readme.adoc
  test/case/infix_services/ssh_key_authentication/test.py
  test/case/infix_services/ssh_key_authentication/topology.dot
  test/case/infix_services/ssh_key_authentication/topology.svg
  test/case/infix_services/ssh_server_config/Readme.adoc
  test/case/infix_services/ssh_server_config/test.py
  test/case/infix_services/ssh_server_config/topology.dot
  test/case/infix_services/ssh_server_config/topology.svg
  test/infamy/restconf.py
Labels: feature
