Repository kernelkit/infix, pull requests merged in 2024-11, with the labels that each got.

#826 Container fixes
  board/common/rootfs/etc/finit.d/available/container@.conf
  board/common/rootfs/etc/profile.d/alias.sh
  board/common/rootfs/usr/bin/cfg
  board/common/rootfs/usr/lib/tmpfiles.d/frr.conf
  board/common/rootfs/usr/libexec/infix/mnt
  board/common/rootfs/usr/sbin/container
  doc/ChangeLog.md
  doc/container.md
  doc/networking.md
  doc/scripting.md
  package/curios-httpd/curios-httpd.hash
  package/curios-httpd/curios-httpd.mk
  package/curios-nftables/curios-nftables.hash
  package/curios-nftables/curios-nftables.mk
  package/execd/execd.conf
  package/execd/tmpfiles.conf
  patches/podman/4.5.0/0001-disable-pull-retry.patch
  src/confd/src/infix-containers.c
  src/confd/yang/confd.inc
  src/confd/yang/containers.inc
  src/confd/yang/infix-containers.yang
  src/confd/yang/infix-containers@2024-11-15.yang
  src/confd/yang/infix-if-bridge.yang
  src/confd/yang/infix-if-bridge@2024-11-15.yang
  src/confd/yang/infix-if-container.yang
  src/confd/yang/infix-if-container@2024-11-15.yang
  src/confd/yang/infix-interfaces.yang
  src/confd/yang/infix-interfaces@2024-11-15.yang
  src/confd/yang/infix-routing.yang
  src/confd/yang/infix-routing@2024-11-15.yang
  src/execd/Makefile.am
  src/execd/execd.c
  src/execd/execd.h
  src/klish-plugin-infix/xml/containers.xml
  test/infamy/container.py
Labels: ci:main

#837 Prevent traffic assigned to locally terminated VLANs from being forwarded
  doc/ChangeLog.md
  doc/networking.md
  patches/linux/6.6.52/0001-net-phy-add-support-for-PHY-LEDs-polarity-modes.patch
  patches/linux/6.6.52/0002-net-mvmdio-Support-setting-the-MDC-frequency-on-XSMI.patch
  patches/linux/6.6.52/0003-net-dsa-mv88e6xxx-Create-API-to-read-a-single-stat-c.patch
  patches/linux/6.6.52/0004-net-dsa-mv88e6xxx-Give-each-hw-stat-an-ID.patch
  patches/linux/6.6.52/0005-net-dsa-mv88e6xxx-Add-eth-mac-counter-group-support.patch
  patches/linux/6.6.52/0006-net-dsa-mv88e6xxx-Limit-histogram-counters-to-ingres.patch
  patches/linux/6.6.52/0007-net-dsa-mv88e6xxx-Add-rmon-counter-group-support.patch
  patches/linux/6.6.52/0009-net-dsa-mv88e6xxx-Add-LED-infrastructure.patch
  patches/linux/6.6.52/0010-net-dsa-mv88e6xxx-Add-LED-support-for-6393X.patch
  patches/linux/6.6.52/0011-net-dsa-mv88e6xxx-Fix-timeout-on-waiting-for-PPU-on-.patch
  patches/linux/6.6.52/0012-net-dsa-Support-MDB-memberships-whose-L2-addresses-o.patch
  patches/linux/6.6.52/0013-net-phy-marvell10g-Support-firmware-loading-on-88X33.patch
  patches/linux/6.6.52/0014-net-phy-marvell10g-Fix-power-up-when-strapped-to-sta.patch
  patches/linux/6.6.52/0015-net-phy-marvell10g-Add-LED-support-for-88X3310.patch
  patches/linux/6.6.52/0016-net-phy-marvell10g-Support-LEDs-tied-to-a-single-med.patch
  patches/linux/6.6.52/0017-nvmem-layouts-onie-tlv-Let-device-probe-even-when-TL.patch
  patches/linux/6.6.52/0018-net-bridge-avoid-classifying-unknown-multicast-as-mr.patch
  patches/linux/6.6.52/0019-net-bridge-Ignore-router-ports-when-forwarding-L2-mu.patch
  patches/linux/6.6.52/0020-net-dsa-Support-EtherType-based-priority-overrides.patch
  patches/linux/6.6.52/0021-net-dsa-mv88e6xxx-Support-EtherType-based-priority-o.patch
  patches/linux/6.6.52/0022-net-phy-Do-not-resume-PHY-when-attaching.patch
  patches/linux/6.6.52/0023-net-dsa-mv88e6xxx-Improve-indirect-register-access-p.patch
  patches/linux/6.6.52/0024-net-bridge-drop-delay-for-applying-strict-multicast-.patch
  patches/linux/6.6.52/0025-net-dsa-mv88e6xxx-Honor-ports-being-managed-via-in-b.patch
  patches/linux/6.6.52/0026-net-dsa-mv88e6xxx-Fix-port-policy-config-on-6393X.patch
  patches/linux/6.6.52/0027-net-dsa-mv88e6xxx-Limit-rsvd2cpu-policy-to-user-port.patch
  patches/linux/6.6.52/0028-usb-core-adjust-log-level-for-unauthorized-devices.patch
  patches/linux/6.6.52/0029-net-dsa-mv88e6xxx-Grab-register-lock-during-counter-.patch
  patches/linux/6.6.52/0030-net-bridge-Differentiate-MDB-additions-from-modifica.patch
  patches/linux/6.6.52/0031-net-dsa-tag_dsa-Use-tag-priority-as-initial-skb-prio.patch
  patches/linux/6.6.52/0032-net-dsa-mv88e6xxx-Add-mqprio-qdisc-support.patch
  patches/linux/6.6.52/0033-net-dsa-mv88e6xxx-Use-VLAN-prio-over-IP-when-both-ar.patch
  patches/linux/6.6.52/0034-net-dsa-mb88e6xxx-use-EOPNOTSUPP-for-unsupported-fla.patch
  patches/linux/6.6.52/0035-net-dsa-mv88e6xxx-Trap-locally-terminated-VLANs.patch
  src/confd/yang/confd.inc
  src/confd/yang/containers.inc
  src/confd/yang/infix-if-bridge.yang
  src/confd/yang/infix-if-bridge@2024-11-28.yang
  src/confd/yang/infix-interfaces.yang
  src/confd/yang/infix-interfaces@2024-11-27.yang
  src/statd/python/yanger/yanger.py
  test/case/cli/cli-output/show-interfaces.txt
  test/case/cli/system-output/bridge-vlan-show-dev-br0.json
  test/case/cli/system-output/bridge-vlan-show-dev-br1.json
  test/case/ietf_interfaces/Readme.adoc
  test/case/ietf_interfaces/ietf_interfaces.yaml
  test/case/ietf_interfaces/vlan_iface_termination/Readme.adoc
  test/case/ietf_interfaces/vlan_iface_termination/test.py
  test/case/ietf_interfaces/vlan_iface_termination/topology.dot
  test/case/ietf_interfaces/vlan_iface_termination/topology.svg
  test/case/use_case/ospf_container/test.py
Labels: ci:main

#832 Initial support for Qemu Rocker switch
  board/common/qemu/Config.in.in
  board/common/qemu/qemu.sh
  board/common/rootfs/etc/default/ospfd
  board/common/rootfs/etc/default/zebra
  board/common/rootfs/usr/bin/pager
  board/common/rootfs/usr/share/udhcpc/default.script
  board/x86_64/linux_defconfig
  package/skeleton-init-finit/skeleton/etc/finit.d/available/frr/ospfd.conf
  package/skeleton-init-finit/skeleton/etc/finit.d/available/frr/zebra.conf
Labels: enhancement

#843 Redesign and simplify container creation/removal
  board/common/rootfs/etc/finit.d/available/container@.conf
  board/common/rootfs/usr/bin/pager
  board/common/rootfs/usr/lib/tmpfiles.d/containers.conf
  board/common/rootfs/usr/sbin/container
  configs/aarch64_defconfig
  configs/r2s_defconfig
  configs/riscv64_defconfig
  configs/x86_64_defconfig
  doc/ChangeLog.md
  package/execd/tmpfiles.conf
  package/finit/0001-Only-mark-rdeps-dirty-if-main-service-is-nohup.patch
  package/finit/0002-Reset-color-attributes-and-clear-screen-when-startin.patch
  package/finit/0003-plugins-refactor-rtc.so.patch
  package/finit/0004-Fix-418-support-systems-with-a-broken-RTC.patch
  package/finit/0005-Fix-buggy-with-rtc-date-DATE-introduced-in-Finit-v4..patch
  package/finit/0006-plugins-reduce-log-level-LOG_ERR-LOG_WARNING.patch
  package/finit/0007-Fix-unintended-restart-of-template-siblings.patch
  package/skeleton-init-finit/skeleton/etc/finit.d/available/avahi.conf
  patches/avahi/0001-On-SIGTERM-allow-dispatcher-to-process-event-before-.patch
  patches/avahi/0002-avahi-daemon-allow-adjusting-log-level.patch
  patches/libdaemon/0.14/0001-dlog-adjust-syslog-level-in-daemon_set_verbosity-too.patch
  patches/podman/4.5.0/0001-disable-pull-retry.patch
  src/confd/src/ietf-interfaces.c
  src/confd/src/infix-containers.c
  src/klish-plugin-infix/xml/containers.xml
  src/klish-plugin-infix/xml/infix.xml
Labels: ci:main

#844 Final ChangeLog updates for v24.11.1
  doc/ChangeLog.md
Labels: documentation
